### ISSUE TITLE
Complete UI mocks

### ISSUE THREAD

**Issue by ihsan314** [cloudlockr/cloudlockr-app#3]
The current mock-up looks like this:
![GUI Mock of CloudLockr App](https://lh5.googleusercontent.com/9l8dzWCTYg03_uOg4DVP9BPbIVFI8CvK_WDh58yl1-r9OeERlKKqzXJFhmmrOaCdun_FgC_8oEdRST35l5CQz5ilf8pV9hcBgm69EkM4eYcM3DaUcE7WFpnvEJHB6fIuzYbQw4h4)

Once we decide on the final views of the UI, then skeleton implementations can be done.

**Comment by zfrantzen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Finalize Figma designs](https://trello.com/c/RG9wjTk6/12-finalize-figma-designs)

**Comment by zfrantzen** [comment]
Here's the complete mockup
![Complete Mockup](https://user-images.githubusercontent.com/43505724/107443769-4a862c80-6aee-11eb-8577-49a7ce36314e.png)
