### ISSUE TITLE
Set up CI/CD (mainly for testing)

### ISSUE THREAD

**Issue by ihsan314** [cloudlockr/cloudlockr-app#6]
Travis CI should probably work well for CI/CD with React Native and Jest, but if not we can fall back on GitHub Actions. We should probably have CI/CD running on each commit.

**Comment by zfrantzen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service testing / CI implementation / README update](https://trello.com/c/lNZtWZyV/32-service-testing-ci-implementation-readme-update)
